<?php

declare(strict_types=1);

$page = static fn (
    string $path,
    string $target,
    string $name,
    array $middleware = [],
    array $methods = ['GET', 'POST']
): array => compact('methods', 'path', 'target', 'name', 'middleware');

return [
    $page('/', 'index.php', 'home'),
    $page('/home', 'index.php', 'home.legacy'),
    $page('/sistema-cashback', 'index.php', 'marketing.cashback'),
    $page('/cashback-brasil', 'index.php', 'marketing.cashback-brasil'),
    $page('/programa-fidelidade', 'index.php', 'marketing.fidelidade'),
    $page('/login', 'views/auth/login.php', 'auth.login', ['guest']),
    $page('/registro', 'views/auth/register.php', 'auth.register', ['guest']),
    $page('/recuperar-senha', 'views/auth/recover-password.php', 'auth.recover', ['guest']),
    $page('/logout', 'views/auth/logout.php', 'auth.logout', ['auth']),
    $page('/como-funciona', 'views/marketing/como-funciona.php', 'marketing.how'),
    $page('/vantagens-cashback', 'views/marketing/vantagens.php', 'marketing.benefits'),
    $page('/blog', 'views/blog/index.php', 'blog.index', [], ['GET']),
    $page('/blog/{slug:[a-zA-Z0-9-]+}', 'views/blog/post.php', 'blog.post', [], ['GET']),
    $page('/categoria/{slug:[a-zA-Z0-9-]+}', 'views/blog/categoria.php', 'blog.category', [], ['GET']),
    $page('/cadastro-loja', 'views/stores/register.php', 'store.register'),
    $page('/seja-parceiro', 'views/stores/register.php', 'store.partner'),
    $page('/parceria-comercial', 'views/stores/register.php', 'store.commercial-partner'),
    $page('/lojas/cadastro', 'views/stores/register.php', 'store.register.canonical'),
    $page('/lojas/detalhes/{id:\\d+}', 'views/stores/details.php', 'store.details', [], ['GET', 'POST']),
    $page('/cliente/dashboard', 'views/client/dashboard.php', 'client.dashboard', ['client']),
    $page('/cliente/extrato', 'views/client/statement.php', 'client.statement', ['client']),
    $page('/cliente/lojas-parceiras', 'views/client/partner-stores.php', 'client.stores', ['client']),
    $page('/cliente/perfil', 'views/client/profile.php', 'client.profile', ['client']),
    $page('/cliente/saldo', 'views/client/balance.php', 'client.balance', ['client']),
    $page('/cliente/actions', 'controllers/client_actions.php', 'client.actions', ['client']),
    $page('/loja/hub', 'views/client/partner-stores.php', 'client.hub', ['client']),
    $page('/loja/autogestao', 'views/client/partner-stores.php', 'client.self-service', ['client']),
    $page('/admin/dashboard', 'views/admin/dashboard.php', 'admin.dashboard', ['admin']),
    $page('/admin/usuarios', 'views/admin/users.php', 'admin.users', ['admin']),
    $page('/admin/lojas', 'views/admin/stores.php', 'admin.stores', ['admin']),
    $page('/admin/transacoes', 'views/admin/purchases.php', 'admin.transactions', ['admin']),
    $page('/admin/transacao/{id:\\d+}', 'views/admin/transaction-details.php', 'admin.transaction', ['admin']),
    $page('/admin/configuracoes', 'views/admin/settings.php', 'admin.settings', ['admin']),
    $page('/admin/saldo', 'views/admin/balance.php', 'admin.balance', ['admin']),
    $page('/admin/comissoes', 'views/admin/commissions.php', 'admin.commissions', ['admin']),
    $page('/admin/pagamentos', 'views/admin/payments.php', 'admin.payments', ['admin']),
    $page('/admin/cashback-config', 'views/admin/cashback-config.php', 'admin.cashback', ['admin']),
    $page('/admin/relatorios', 'views/admin/reports.php', 'admin.reports', ['admin']),
    $page('/admin/assinaturas', 'views/admin/subscriptions.php', 'admin.subscriptions', ['admin']),
    $page('/admin/store-subscription', 'views/admin/store-subscription.php', 'admin.store-subscription', ['admin']),
    $page('/admin/email-marketing', 'views/admin/email-marketing.php', 'admin.email-marketing', ['admin']),
    $page('/admin/email-templates', 'views/admin/email-templates.php', 'admin.email-templates', ['admin']),
    $page('/admin/ajax/stores', 'controllers/AdminController.php', 'admin.ajax.stores', ['admin']),
    $page('/admin/ajax/users', 'controllers/AdminController.php', 'admin.ajax.users', ['admin']),
    $page('/admin/ajax/transactions', 'controllers/AdminController.php', 'admin.ajax.transactions', ['admin']),
    $page('/admin/ajax/stores-direct', 'controllers/AjaxStoreController.php', 'admin.ajax.stores-direct', ['admin']),
    $page('/admin/ajax/auth', 'controllers/AuthController.php', 'admin.ajax.auth', ['admin']),
    $page('/admin/ajax/store-controller', 'controllers/StoreController.php', 'admin.ajax.store-controller', ['admin']),
    $page('/admin/ajax/transaction-controller', 'controllers/TransactionController.php', 'admin.ajax.transaction-controller', ['admin']),
    $page('/admin/ajax/store-balance-payments', 'controllers/StoreBalancePaymentController.php', 'admin.ajax.store-balance-payments', ['admin']),
    $page('/cliente/ajax/controller', 'controllers/ClientController.php', 'client.ajax.controller', ['client']),
    $page('/store', 'views/stores/dashboard.php', 'store.home', ['store']),
    $page('/store/dashboard', 'views/stores/dashboard.php', 'store.dashboard', ['store']),
    $page('/store/transacoes', 'views/stores/transactions.php', 'store.transactions', ['store']),
    $page('/store/transacoes-pendentes', 'views/stores/pending-commissions.php', 'store.pending', ['store']),
    $page('/store/registrar-transacao', 'views/stores/register-transaction.php', 'store.transaction.create', ['store']),
    $page('/store/upload-lote', 'views/stores/batch-upload.php', 'store.batch', ['store']),
    $page('/store/pagamento', 'views/stores/payment.php', 'store.payment', ['store']),
    $page('/store/pagamento-pix', 'views/stores/payment-pix.php', 'store.payment-pix', ['store']),
    $page('/store/historico-pagamentos', 'views/stores/payment-history.php', 'store.payment-history', ['store']),
    $page('/store/perfil', 'views/stores/profile.php', 'store.profile', ['store']),
    $page('/store/meu-plano', 'views/stores/subscription.php', 'store.subscription', ['store']),
    $page('/store/fatura-pix', 'views/stores/invoice-pix.php', 'store.invoice-pix', ['store']),
    $page('/store/funcionarios', 'views/stores/employees.php', 'store.employees', ['store']),
    $page('/robots.txt', 'robots.php', 'robots', [], ['GET']),
    $page('/sitemap.xml', 'sitemap.php', 'sitemap', [], ['GET']),
    $page('/politica-de-privacidade', 'politica-de-privacidade.php', 'privacy', [], ['GET']),
];
