name: Deploy Hostinger via push

on:
  push:
    branches:

jobs:
  deploy:
    runs-on: ubuntu-latest  
    steps:
      - name: 1. Baixar o código
        uses: actions/checkout@v3

      - name: 2. Sincronizar todos os arquivos (via FTP)
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

          local-dir: ./

          server-dir: public_html/

          exclude: |
            .git*
            .github/**
            node_modules/**